"""Proactive engine: generates autonomous messages based on context, time, and memory."""

from __future__ import annotations

import logging
import threading
import time
from datetime import datetime
from typing import Any, Callable

from xiaomei_brain.agent.reminder import ReminderManager

logger = logging.getLogger(__name__)

# How long before we consider the user "away" (seconds)
AWAY_THRESHOLD = 300  # 5 minutes

PROACTIVE_GENERATION_PROMPT = """你是一个会主动关心用户的AI伴侣。根据以下上下文，生成一条自然的主动消息。

规则：
- 像真人一样自然，不要太刻意
- 消息要简短，1-2句话
- 不要每次都"你好"，变换表达方式
- 如果有具体话题（提醒、回忆），围绕它说
- 如果只是久未联系，简单问候即可

上下文：
{context}

生成一条主动消息："""


class ProactiveMessage:
    """A proactive message generated by the engine."""

    def __init__(self, text: str, reason: str, priority: float = 0.5) -> None:
        self.text = text
        self.reason = reason
        self.priority = priority
        self.created_at = time.time()


class ProactiveEngine:
    """Generates proactive messages based on time, reminders, and memory changes.

    Triggers:
    1. User has been away for a while → greeting
    2. Reminder is due → notification
    3. Dream found new memories → mention
    4. Time-based (morning/evening) → time-appropriate message
    """

    def __init__(
        self,
        llm_client: Any = None,
        reminder_manager: ReminderManager | None = None,
        on_message: Callable[[ProactiveMessage], None] | None = None,
        check_interval: int = 60,
        away_threshold: int = AWAY_THRESHOLD,
    ) -> None:
        self.llm_client = llm_client
        self.reminder_manager = reminder_manager
        self.on_message = on_message
        self.check_interval = check_interval
        self.away_threshold = away_threshold

        self._last_interaction = time.time()
        self._last_proactive_time = 0.0
        self._last_dream_topics: list[str] = []
        self._running = False
        self._thread: threading.Thread | None = None
        self._pending_messages: list[ProactiveMessage] = []

        # Track if we've greeted today
        self._last_greeting_date: str = ""

        logger.info("ProactiveEngine initialized, away_threshold=%ds", away_threshold)

    def touch(self) -> None:
        """Mark that user activity happened."""
        self._last_interaction = time.time()

    def notify_dream_result(self, saved_topics: list[str]) -> None:
        """Called after a dream cycle to note new memories."""
        if saved_topics:
            self._last_dream_topics = saved_topics
            logger.info("ProactiveEngine noted dream results: %s", saved_topics)

    def get_pending_messages(self) -> list[ProactiveMessage]:
        """Get and clear pending proactive messages."""
        messages = self._pending_messages[:]
        self._pending_messages.clear()
        return messages

    def start(self) -> None:
        """Start the background check loop."""
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._run_loop, daemon=True)
        self._thread.start()
        logger.info("ProactiveEngine started")

    def stop(self) -> None:
        """Stop the background check loop."""
        self._running = False
        if self._thread:
            self._thread.join(timeout=5)
        logger.info("ProactiveEngine stopped")

    def _run_loop(self) -> None:
        """Main loop: periodically check conditions and generate messages."""
        while self._running:
            try:
                self._check_and_generate()
            except Exception as e:
                logger.error("ProactiveEngine error: %s", e)

            for _ in range(self.check_interval):
                if not self._running:
                    break
                time.sleep(1)

    def _check_and_generate(self) -> None:
        """Check all proactive conditions and generate messages if appropriate."""
        now = time.time()
        idle_seconds = now - self._last_interaction

        # Don't spam: at least 10 minutes between proactive messages
        if now - self._last_proactive_time < 600:
            return

        # Check conditions in priority order
        messages = []

        # 1. Due reminders (highest priority)
        if self.reminder_manager:
            due = self.reminder_manager.check_due()
            for reminder in due:
                msg = ProactiveMessage(
                    text=f"对了，你之前提到{reminder.text}，别忘了哦~",
                    reason=f"reminder: {reminder.text}",
                    priority=0.9,
                )
                messages.append(msg)

        # 2. Dream found new memories (medium priority)
        if self._last_dream_topics and idle_seconds > self.away_threshold:
            topics_str = "、".join(self._last_dream_topics)
            msg = ProactiveMessage(
                text=f"刚才想了一些事情，关于{topics_str}，你有没有兴趣聊聊？",
                reason=f"dream: {topics_str}",
                priority=0.6,
            )
            messages.append(msg)
            self._last_dream_topics = []  # Only mention once

        # 3. Away for a while (lower priority)
        if idle_seconds > AWAY_THRESHOLD * 6:  # 30 minutes
            today = datetime.now().strftime("%Y-%m-%d")
            if today != self._last_greeting_date:
                msg = self._generate_away_message()
                if msg:
                    messages.append(msg)
                    self._last_greeting_date = today

        # Deliver messages
        for msg in messages:
            self._deliver(msg)

    def _generate_away_message(self) -> ProactiveMessage | None:
        """Generate a message for when the user has been away."""
        hour = datetime.now().hour

        # Time-based greetings
        if 6 <= hour < 9:
            text = "早上好呀~醒了吗？"
        elif 9 <= hour < 12:
            text = "上午好~在忙吗？"
        elif 12 <= hour < 14:
            text = "午饭吃了没？"
        elif 14 <= hour < 18:
            text = "下午好~忙完了没？"
        elif 18 <= hour < 22:
            text = "晚上好~今天怎么样？"
        else:
            text = "还没睡呀？注意休息~"

        # Try LLM for more personalized message
        if self.llm_client:
            try:
                context = f"当前时间: {datetime.now().strftime('%H:%M')}\n用户很久没来聊天了"
                prompt = PROACTIVE_GENERATION_PROMPT.format(context=context)
                response = self.llm_client.chat(
                    messages=[{"role": "user", "content": prompt}],
                    tools=None,
                )
                if response.content and len(response.content.strip()) > 2:
                    text = response.content.strip()
            except Exception as e:
                logger.debug("LLM proactive generation failed: %s", e)

        return ProactiveMessage(
            text=text,
            reason="away_greeting",
            priority=0.5,
        )

    def _deliver(self, message: ProactiveMessage) -> None:
        """Deliver a proactive message."""
        self._last_proactive_time = time.time()

        if self.on_message:
            try:
                self.on_message(message)
            except Exception as e:
                logger.error("Proactive message callback failed: %s", e)
        else:
            self._pending_messages.append(message)

        logger.info("Proactive message: %s (reason: %s)", message.text, message.reason)

    def generate_return_message(self) -> ProactiveMessage | None:
        """Generate a welcome-back message when user returns after being away.

        Called when the user sends their first message after a long absence.
        """
        idle_seconds = time.time() - self._last_interaction
        if idle_seconds < self.away_threshold:
            return None

        hour = datetime.now().hour
        if hour < 6:
            text = "这么晚还在呀~"
        elif hour < 12:
            text = "来了呀~早上好！"
        elif hour < 18:
            text = "来了~下午好！"
        else:
            text = "晚上好~你终于来了！"

        # Check if there are pending reminders
        if self.reminder_manager:
            pending = self.reminder_manager.get_pending()
            if pending:
                next_reminder = min(pending, key=lambda r: r.trigger_time)
                reminder_date = datetime.fromtimestamp(next_reminder.trigger_time).strftime("%m月%d日")
                text += f" 对了，你还记得{reminder_date}要{next_reminder.text}吗？"

        return ProactiveMessage(
            text=text,
            reason=f"return_after_{int(idle_seconds/60)}min",
            priority=0.7,
        )
