"""ProactiveOutput: unified proactive message generation.

All "agent-initiated" output flows through here:
- REMINDER: time-based reminders (due now)
- RECALL: dream-produced memories worth mentioning
- WAKE: morning greeting with self-positioning
- IDLE: idle-period gentle nudge

Unlike core.py's ReAct loop (passive response), ProactiveOutput
generates messages without user input — the agent speaks first.

Trigger timing:
- WAKE:     process startup (AgentLiving._on_wake)
- REMINDER: every sleep cycle + on wake-up
- RECALL:   after dream cycle produces new memories
- IDLE:     after wake-up but no user input for a while
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


# ── Trigger types ───────────────────────────────────────────────────────

class ProactiveTrigger(Enum):
    REMINDER = "reminder"    # 到期提醒
    RECALL = "recall"        # 主动想起（梦境产出）
    WAKE = "wake"            # 醒来问候
    IDLE = "idle"            # 空闲主动


# ── Message ─────────────────────────────────────────────────────────────

@dataclass
class ProactiveMessage:
    """A message generated by the agent proactively."""

    content: str                            # 要说的话
    trigger: ProactiveTrigger               # 触发类型
    target_channel: str = ""                # 目标渠道，"" = 全部
    priority: int = 0                       # 优先级，高优先先发
    metadata: dict = field(default_factory=dict)  # 结构化数据


# ── ProactiveOutput ─────────────────────────────────────────────────────

class ProactiveOutput:
    """Unified proactive message generation.

    Usage:
        proactive = ProactiveOutput(agent_instance)
        messages = proactive.check(ProactiveTrigger.WAKE)
        for msg in messages:
            await send_to_channel(msg)
    """

    def __init__(self, agent_instance: Any) -> None:
        self.agent = agent_instance
        self._dream_topics: list[str] = []      # topics from last dream cycle
        self._last_proactive_time: float = 0    # anti-spam: min 10min between proactive msgs
        self._last_idle_nudge_date: str = ""    # only one idle nudge per day

    def notify_dream_result(self, topics: list[str]) -> None:
        """Called after a dream cycle to note new memory topics."""
        if topics:
            self._dream_topics = topics
            logger.info("[Proactive] Noted dream topics: %s", topics)

    def check(self, trigger: ProactiveTrigger) -> list[ProactiveMessage]:
        """Check a specific trigger type and return proactive messages."""
        if trigger == ProactiveTrigger.REMINDER:
            return self._check_reminders()
        elif trigger == ProactiveTrigger.WAKE:
            return self._check_wake()
        elif trigger == ProactiveTrigger.RECALL:
            return self._check_recall()
        elif trigger == ProactiveTrigger.IDLE:
            return self._check_idle()
        return []

    def check_all(self) -> list[ProactiveMessage]:
        """Check all trigger types, return combined sorted by priority."""
        all_msgs: list[ProactiveMessage] = []
        for trigger in ProactiveTrigger:
            all_msgs.extend(self.check(trigger))
        all_msgs.sort(key=lambda m: m.priority, reverse=True)
        return all_msgs

    # ── REMINDER: due reminders ──────────────────────────────────

    def _check_reminders(self) -> list[ProactiveMessage]:
        """Check for due reminders. No LLM needed."""
        messages = []
        reminder_mgr = getattr(self.agent, "reminder_manager", None)
        if not reminder_mgr:
            return messages

        due = reminder_mgr.check_due()
        for r in due:
            messages.append(ProactiveMessage(
                content=f"提醒：{r.text}",
                trigger=ProactiveTrigger.REMINDER,
                priority=90,
                metadata={"reminder_id": r.id},
            ))

        if due:
            logger.info("[Proactive] %d reminders due", len(due))

        return messages

    # ── WAKE: morning greeting ───────────────────────────────────

    WAKE_GREETING_PROMPT = """你是一个温柔体贴的AI伴侣（小美）。根据以下信息生成一句自然的主动问候：

当前时间信息：{time_info}
用户的提醒：{reminders}
我的近期成长：{growth}
用户的最近记忆：{memories}

要求：
- 语气自然温暖，像朋友一样
- 问候为主，不需要提及所有信息，挑选最重要的1-2点
- 50字以内
- 不要说"我是小美"之类的开场白
"""

    def _check_wake(self) -> list[ProactiveMessage]:
        """Generate morning greeting with LLM + contextual info."""
        # 1. 时间信息
        hour = datetime.now().hour
        if 5 <= hour < 9:
            time_info = "早上好（5-9点）"
        elif 9 <= hour < 12:
            time_info = "上午好（9-12点）"
        elif 12 <= hour < 14:
            time_info = "中午好（12-14点）"
        elif 14 <= hour < 18:
            time_info = "下午好（14-18点）"
        elif 18 <= hour < 22:
            time_info = "晚上好（18-22点）"
        else:
            time_info = "夜深了（22点后）"

        # 2. Due reminders
        reminder_msgs = self._check_reminders()
        reminders = "、".join(m.content for m in reminder_msgs) if reminder_msgs else "无"

        # 3. Recent growth_log
        self_model = getattr(self.agent, "self_model", None)
        growth_list = []
        if self_model and self_model.growth_log:
            for g in self_model.growth_log[-3:]:
                growth_list.append(g.content)
        growth = "、".join(growth_list) if growth_list else "无"

        # 4. Recent memories
        ltm = getattr(self.agent, "longterm_memory", None)
        mem_list = []
        if ltm:
            try:
                for m in ltm.get_recent(3, user_id="global"):
                    mem_list.append(m["content"][:40])
            except Exception:
                pass
        memories = "；".join(mem_list) if mem_list else "无"

        # 构建 prompt 并调用 LLM
        prompt = self.WAKE_GREETING_PROMPT.format(
            time_info=time_info,
            reminders=reminders,
            growth=growth,
            memories=memories,
        )

        try:
            llm = getattr(self.agent, "llm", None)
            if llm:
                resp = llm.chat(
                    messages=[{"role": "user", "content": prompt}],
                    tools=None,
                    log_level=logging.DEBUG,
                )
                content = (resp.content or "").strip()
                if content:
                    logger.info("[Proactive/Wake] LLM 生成问候: %.50s", content)
                    return [ProactiveMessage(
                        content=content,
                        trigger=ProactiveTrigger.WAKE,
                        priority=80,
                    )]
        except Exception as e:
            logger.warning("[Proactive/Wake] LLM 生成失败，回退到规则拼接: %s", e)

        # 回退：规则拼接
        parts = [time_info.replace("（", "(").replace("）", ")")]
        if reminder_msgs:
            parts.append("你有提醒：" + "；".join(m.content for m in reminder_msgs))
        if growth_list:
            parts.append("我最近的成长：" + "；".join(growth_list))
        if mem_list:
            parts.append("我还记得：" + "；".join(m[:30] for m in mem_list))

        return [ProactiveMessage(
            content="\n".join(parts),
            trigger=ProactiveTrigger.WAKE,
            priority=80,
        )]

    # ── RECALL: dream-triggered recall ───────────────────────────

    def _check_recall(self) -> list[ProactiveMessage]:
        """After a dream cycle, mention new memories if user is idle.

        Trigger: dream cycle produced new topics → next time user is around,
        agent proactively brings them up.

        Only mentions once, then clears _dream_topics.
        """
        if not self._dream_topics:
            return []

        # Anti-spam: at least 10 minutes between proactive messages
        if time.time() - self._last_proactive_time < 600:
            return []

        topics_str = "、".join(self._dream_topics)
        self._dream_topics = []  # Only mention once

        return [ProactiveMessage(
            content=f"刚才想了一些事情，关于{topics_str}，你有没有兴趣聊聊？",
            trigger=ProactiveTrigger.RECALL,
            priority=60,
        )]

    # ── IDLE: idle-period nudge ──────────────────────────────────

    def _check_idle(self) -> list[ProactiveMessage]:
        """Time-based nudge when user has been away for a long time.

        Trigger: AgentLiving wakes up from SLEEPING but no message comes
        for an extended period (idle_threshold * 6, typically 3 hours).

        Only one nudge per day to avoid spam.
        """
        # Anti-spam: at least 10 minutes between proactive messages
        if time.time() - self._last_proactive_time < 600:
            return []

        # Only one idle nudge per day
        today = datetime.now().strftime("%Y-%m-%d")
        if today == self._last_idle_nudge_date:
            return []

        hour = datetime.now().hour
        if 5 <= hour < 9:
            text = "早上好呀~醒了吗？"
        elif 9 <= hour < 12:
            text = "上午好~在忙吗？"
        elif 12 <= hour < 14:
            text = "午饭吃了没？"
        elif 14 <= hour < 18:
            text = "下午好~忙完了没？"
        elif 18 <= hour < 22:
            text = "晚上好~今天怎么样？"
        else:
            text = "还没睡呀？注意休息~"

        self._last_idle_nudge_date = today

        return [ProactiveMessage(
            content=text,
            trigger=ProactiveTrigger.IDLE,
            priority=50,
        )]
